//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Input/HexGameControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @HexGameControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @HexGameControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""HexGameControls"",
    ""maps"": [
        {
            ""name"": ""Move"",
            ""id"": ""64a08479-2243-48d0-b650-0e36584d8972"",
            ""actions"": [
                {
                    ""name"": ""SelectHex"",
                    ""type"": ""Button"",
                    ""id"": ""f0b8b4d7-f5b3-4e3b-97bc-633087055ed0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""511ffaaa-4f16-4470-b456-61c8627e088e"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectHex"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Move
        m_Move = asset.FindActionMap("Move", throwIfNotFound: true);
        m_Move_SelectHex = m_Move.FindAction("SelectHex", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Move
    private readonly InputActionMap m_Move;
    private IMoveActions m_MoveActionsCallbackInterface;
    private readonly InputAction m_Move_SelectHex;
    public struct MoveActions
    {
        private @HexGameControls m_Wrapper;
        public MoveActions(@HexGameControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @SelectHex => m_Wrapper.m_Move_SelectHex;
        public InputActionMap Get() { return m_Wrapper.m_Move; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MoveActions set) { return set.Get(); }
        public void SetCallbacks(IMoveActions instance)
        {
            if (m_Wrapper.m_MoveActionsCallbackInterface != null)
            {
                @SelectHex.started -= m_Wrapper.m_MoveActionsCallbackInterface.OnSelectHex;
                @SelectHex.performed -= m_Wrapper.m_MoveActionsCallbackInterface.OnSelectHex;
                @SelectHex.canceled -= m_Wrapper.m_MoveActionsCallbackInterface.OnSelectHex;
            }
            m_Wrapper.m_MoveActionsCallbackInterface = instance;
            if (instance != null)
            {
                @SelectHex.started += instance.OnSelectHex;
                @SelectHex.performed += instance.OnSelectHex;
                @SelectHex.canceled += instance.OnSelectHex;
            }
        }
    }
    public MoveActions @Move => new MoveActions(this);
    public interface IMoveActions
    {
        void OnSelectHex(InputAction.CallbackContext context);
    }
}
