using System;
using System.Collections.Generic;
using System.Linq;
using SuperHexLink.Simulation;

namespace SuperHexLink.Integration
{
    /// <summary>
    /// Converts between Unity's GameSpawner scene state and the Unity-free HeadlessGameState.
    /// Enables Monte Carlo simulation and AI rule testing against live board data.
    /// </summary>
    public static class UnityGameStateBridge
    {
        // Maps Unity hex type strings to HeadlessGameState ResourceType enum
        private static readonly Dictionary<string, ResourceType> HexTypeToResource =
            new Dictionary<string, ResourceType>(StringComparer.OrdinalIgnoreCase)
            {
                { "forest",   ResourceType.Wood  },
                { "hill",     ResourceType.Brick },
                { "pasture",  ResourceType.Sheep },
                { "field",    ResourceType.Wheat },
                { "mountain", ResourceType.Ore   },
                { "gold",     ResourceType.Gold  }
                // "sea", "harbour", "desert" — no production, skipped
            };

        /// <summary>
        /// Extracts a Unity-free game state from the current scene.
        /// Reads hex type and production number data from the spawner;
        /// player count defaults to <paramref name="playerCount"/>.
        /// </summary>
        /// <param name="spawner">The active GameSpawner MonoBehaviour.</param>
        /// <param name="hexSpawnerState">The current HexSpawner state (from hexSpawner.State).</param>
        /// <param name="playerCount">Number of players (defaults to 4).</param>
        public static HeadlessGameState ExtractFromScene(
            GameSpawner.GameSpawnerState gameState,
            HexSpawner.HexSpawnerState hexSpawnerState,
            int playerCount = 4)
        {
            if (gameState == null) throw new ArgumentNullException(nameof(gameState));
            if (hexSpawnerState == null) throw new ArgumentNullException(nameof(hexSpawnerState));

            int cols = Math.Max(1, gameState.hexGridConfig.cols);
            int rows = Math.Max(1, gameState.hexGridConfig.rows);

            // Build a HeadlessGameState sized to the scene's grid
            var state = HeadlessGameState.CreateInitialState(playerCount, cols, rows);

            // Overwrite hex data with real scene values
            var hexes = new Dictionary<int, HexData>();
            if (hexSpawnerState.hexes != null)
            {
                foreach (var row in hexSpawnerState.hexes)
                {
                    if (row == null) continue;
                    foreach (var hexState in row)
                    {
                        if (hexState == null) continue;
                        var hexId = hexState.Col * rows + hexState.Row;
                        hexes[hexId] = new HexData
                        {
                            HexId          = hexId,
                            Q              = hexState.Col,
                            R              = hexState.Row,
                            ResourceType   = MapHexTypeToResource(hexState.HexType),
                            ProductionNumber = hexState.HexNum ?? 0,
                            ExhaustionLevel = 0
                        };
                    }
                }
            }

            // Replace the random grid generated by CreateInitialState with real data
            // (struct copy semantics require rebuilding via Clone pattern)
            var grid = state.HexGrid;
            foreach (var kvp in hexes)
            {
                grid.Hexes[kvp.Key] = kvp.Value;
            }
            // Re-assign back (struct field)
            state = new HeadlessGameState
            {
                HexGrid       = grid,
                Players       = state.Players,
                CurrentTurn   = state.CurrentTurn,
                GamePhase     = state.GamePhase,
                VictoryState  = state.VictoryState,
                EconomicState = state.EconomicState
            };

            return state;
        }

        /// <summary>
        /// Applies a simulation state back to the Unity spawner state.
        /// Updates the grid configuration; call <c>spawner.BuildMe(true)</c> afterwards
        /// to propagate changes to the actual Unity GameObjects.
        /// </summary>
        /// <param name="state">The simulation state to apply.</param>
        /// <param name="gameState">The GameSpawnerState to update in-place.</param>
        public static void ApplyToScene(HeadlessGameState state, GameSpawner.GameSpawnerState gameState)
        {
            if (gameState == null) throw new ArgumentNullException(nameof(gameState));

            // Update grid dimensions from the simulation state
            int maxQ = state.HexGrid.Hexes.Values.Select(h => h.Q).DefaultIfEmpty(0).Max() + 1;
            int maxR = state.HexGrid.Hexes.Values.Select(h => h.R).DefaultIfEmpty(0).Max() + 1;

            if (maxQ > 0 && maxR > 0)
            {
                gameState.hexGridConfig = new HexGridConfig
                {
                    cols = maxQ,
                    rows = maxR
                };
            }

            // Rebuild land configs to match the hex resource distribution
            var landCounts = new Dictionary<string, int>(StringComparer.OrdinalIgnoreCase);
            foreach (var hex in state.HexGrid.Hexes.Values)
            {
                var landType = MapResourceToHexType(hex.ResourceType);
                if (!landCounts.ContainsKey(landType)) landCounts[landType] = 0;
                landCounts[landType]++;
            }

            gameState.landConfigs = landCounts
                .Select(kvp => new GameSpawner.LandConfig
                {
                    landGroupID = "1",
                    landCnt     = kvp.Value,
                    landType    = kvp.Key
                })
                .ToList();
        }

        // ── Helpers ───────────────────────────────────────────────────────────────

        private static ResourceType MapHexTypeToResource(string hexType)
        {
            if (hexType != null && HexTypeToResource.TryGetValue(hexType, out var resourceType))
                return resourceType;
            return ResourceType.Wood; // Default for unknown types (sea/desert/harbour produce nothing)
        }

        private static string MapResourceToHexType(ResourceType resourceType)
        {
            return resourceType switch
            {
                ResourceType.Wood  => "forest",
                ResourceType.Brick => "hill",
                ResourceType.Sheep => "pasture",
                ResourceType.Wheat => "field",
                ResourceType.Ore   => "mountain",
                ResourceType.Gold  => "gold",
                _                  => "desert"
            };
        }
    }
}
